#!/bin/sh

while true; do

 	dbus-send --system --type=method_call --print-reply --dest=net.connman / net.connman.Manager.GetProperties | grep "ready\|online" > /dev/null

	if [ $? -eq 0 ] ; then
		exit 0
	fi

	usleep 200000

done
