#!/bin/sh

echo "Setting CPU governor to performance"
for c in /sys/devices/system/cpu/cpu* ; do
    test -f $c/cpufreq/scaling_governor && \
        /bin/echo performance > $c/cpufreq/scaling_governor
done

exit 0

