#!/bin/sh

#Listen to ServicesChanged signal from dbus
interface=net.connman.Manager
member=ServicesChanged

# Enable connman agent to connect to protected Wifi
connmanctl << EOF
agent on
EOF

/usr/bin/dbus-monitor --system --profile "interface='$interface',member='$member'" |
while read -r line; do

        echo "Connman services changed"

        (
        for con in $(ls /var/lib/connman|grep -v settings) ; do
                dev=$(echo $con|cut -d '_' -f 1)
                if [ "$dev" = "lo" ] ; then continue; fi
                if [ "$dev" = "sit0" ] ; then continue; fi
                mac=$(echo $con|cut -d '_' -f 2)
                echo "Found connection medium: $dev with addr: $mac, Force connect."
                /usr/bin/dbus-send --system --type=method_call --print-reply --dest=net.connman /net/connman/service/$con net.connman.Service.Connect
        done
        );

done

