#!/bin/sh

#Listen to ServicesChanged signal from dbus
interface=net.connman.Manager
member=ServicesChanged

/usr/bin/dbus-monitor --system --profile "interface='$interface',member='$member'" |
while read -r line; do

        echo "Connman services changed"

        (
        cd /sys/class/net
        for dev in * ; do
                if [ "$dev" = "lo" ] ; then continue; fi
                if [ "$dev" = "sit0" ] ; then continue; fi
                mac=$(sed 's/://g' < /sys/class/net/$dev/address)
                echo "Found interface: $dev with addr: $mac, Force connect."
                /usr/bin/dbus-send --system --type=method_call --print-reply --dest=net.connman /net/connman/service/ethernet_${mac}_cable net.connman.Service.Connect
        done
        );

done
